# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Ping
version:      2.39
version_from: lib/Net/Ping.pm
installdirs:  perl
requires:
    Test:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
